### ISSUE TITLE
final project sample code

### ISSUE THREAD

**Issue by windstormer** [HSNL-TAs/2015-ICTN-Final-Project-FTP-Proxy#1]
請問助教,final project給的sample code之中
是否已經有支援完整傳輸功能,
還是只有做到連線的部分呢???
因為我們利用sample code來當proxy進行上傳以及下載時
檔案大小都只能到13MB左右

除了implement rate_control的function
我們是否需要對sample code 做修改...

還請給予多一點提示~~tks

**Comment by lockys** [comment]
@windstormer
感謝你的回報，這是 sample code 的 bug 
@qoo392 已在 765e50bee53e703001f6ef352b0363f5d45306eb commit 作修正
請 pull 最新的 code
如果有其他 bug 歡迎在提出 :+1:

**Comment by qoojung** [comment]
我們已經在 0730b465a21acf2fcd9e13db3148d29b7706ff80 commit
完成最終修正，完成上下載測試
請使用 `git pull` 來下載最新的code
如果有問題歡迎提出
謝謝同學的回報
